services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbdiff
    ports:
      - "3306:3306"
  mariadb:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: dbdiff
    ports:
      - "3307:3306"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbdiff
    ports:
      - "5432:5432"
